spring:
  application:
    name: airline-ticket-booking-system
  datasource:
    url: jdbc:mysql://localhost:3306/airlines_db
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
server:
  port: 9000
